package jp.blogspot.turanukimaru.fehs

/**
 * ロケールで使い分ける名前
 * Created by turanukimaru on 2017/12/23.
 * 注意！！NONE以外に空文字を設定するとなんかの拍子にそれが出てくる
 * Mapに突っ込むときにテストするかなあ
 *
 **/

enum class SkillName(val jp: String, val us: String, val tw: String) {
    NONE("", "", ""),
    Absorb("アブゾーブ", "Absorb", "吸收"),
    Absorb2("アブゾーブ＋", "Absorb+", "吸收＋"),
    Alondite("エタルド", "Alondite", "艾塔爾德"),
    Amiti("アミーテ", "Amiti", "亞米特"),
    Armoads("アルマーズ", "Armoads", "阿爾瑪茲"),
    ArmorSlayer("アーマーキラー", "Armor Slayer", "破甲劍"),
    ArmorSlayer2("アーマーキラー＋", "Armor Slayer+", "破甲劍＋"),
    Armorsmasher("アーマーキラー鍛", "Armorsmasher+", "破甲劍鍛"),
    Armorsmasher2("アーマーキラー鍛＋", "Armorsmasher+", "破甲劍鍛＋"),
    AssassinsBow("暗器殺しの弓", "Assassins Bow", "破暗器之弓"),
    AssassinsBow2("暗器殺しの弓＋", "Assassins Bow+", "破暗器之弓＋"),
    Assault("アサルト", "Assault", "襲擊"),
    Audhulma("アウドムラ", "Audhulma", "奧德姆拉"),
    Aura("オーラ", "Aura", "輝光"),
    AyrasBlade("瞬閃アイラの剣", "Ayras Blade", "瞬閃艾伊拉之劍"),
    BerkutsLance("ベルクトの槍", "Berkuts Lance", "貝爾克特之槍"),
    BerkutsLance2("ベルクトの槍＋", "Berkuts Lance+", "貝爾克特之槍＋"),
    BindingBlade("封印の剣", "Binding Blade", "封印之劍"),
    Blarblade("ブラーブレード", "Blárblade", "蒼藍之刃"),
    Blarblade2("ブラーブレード＋", "Blárblade+", "蒼藍之刃＋"),
    Blarowl("ブラーアウル", "Blárowl", "蒼藍夜梟"),
    Blarowl2("ブラーアウル＋", "Blárowl+", "蒼藍夜梟＋"),
    Blarraven("ブラーレイヴン", "Blárraven", "蒼藍渡鴉"),
    Blarraven2("ブラーレイヴン＋", "Blárraven+", "蒼藍渡鴉＋"),
    Blarwolf("ブラーウルフ", "Blarwolf", "蒼藍餓狼"),
    Blarwolf2("ブラーウルフ＋", "Blarwolf+", "蒼藍餓狼＋"),
    BlazingDurandal("烈剣デュランダル", "Blazing Durandal", "烈劍迪朗達爾"),
    BlessedBouquet("聖なるブーケ", "Blessed Bouquet", "聖潔花束"),
    BlessedBouquet2("聖なるブーケ＋", "Blessed Bouquet+", "聖潔花束＋"),
    BlueEgg("青の卵", "Blue Egg", "青之卵"),
    BlueEgg2("青の卵＋", "Blue Egg+", "青之卵＋"),
    Bolganone("ボルガノン", "Bolganone", "火山爆焰"),
    Bolganone2("ボルガノン＋", "Bolganone+", "火山爆焰＋"),
    BraveAxe("勇者の斧", "Brave Axe", "勇者之斧"),
    BraveAxe2("勇者の斧＋", "Brave Axe+", "勇者之斧＋"),
    BraveBow("勇者の弓", "Brave Bow", "勇者之弓"),
    BraveBow2("勇者の弓＋", "Brave Bow+", "勇者之弓＋"),
    BraveLance("勇者の槍", "Brave Lance", "勇者之槍"),
    BraveLance2("勇者の槍＋", "Brave Lance+", "勇者之槍＋"),
    BraveSword("勇者の剣", "Brave Sword", "勇者之劍"),
    BraveSword2("勇者の剣＋", "Brave Sword+", "勇者之劍＋"),
    BrightNaginata("白き血の薙刀", "Bright Naginata", "白血薙刀"),
    Brynhildr("ブリュンヒルデ", "Brynhildr", "布倫希爾德"),
    Candelabra("燭台", "Candelabra", "燭台"),
    Candelabra2("燭台＋", "Candelabra+", "燭台＋"),
    Candlelight("キャンドルサービス", "Candlelight", "燭光"),
    Candlelight2("キャンドルサービス＋", "Candlelight+", "燭光＋"),
    CarrotAxe("ニンジンの斧", "Carrot Axe", "胡蘿蔔斧"),
    CarrotAxe2("ニンジンの斧＋", "Carrot Axe+", "胡蘿蔔斧＋"),
    CarrotLance("ニンジンの槍", "Carrot Lance", "胡蘿蔔槍"),
    CarrotLance2("ニンジンの槍＋", "Carrot Lance+", "胡蘿蔔槍＋"),
    ClarissesBow("クライネの弓", "Clarisses Bow", "克萊涅之弓"),
    ClarissesBow2("クライネの弓＋", "Clarisses Bow+", "克萊涅之弓＋"),
    CupidArrow("キューピッドの矢", "Cupid Arrow", "邱比特之弓"),
    CupidArrow2("キューピッドの矢＋", "Cupid Arrow+", "邱比特之弓＋"),
    CursedLance("魔性の槍", "Cursed Lance", "魔性之槍"),
    Cymbeline("シムベリン", "Cymbeline", "辛白林"),
    DancersFan("舞踏祭の扇子", "Dancer's Fan", "舞會摺扇"),
    DancersFan2("舞踏祭の扇子＋", "Dancer's Fan+", "舞會摺扇＋"),
    DancersRing("舞踏祭の輪", "Dancer's Ring", "舞會之環"),
    DancersRing2("舞踏祭の輪＋", "Dancer's Ring+", "舞會之環＋"),
    DancersScore("舞踏祭の楽譜", "Dancer's Score", "舞會樂章"),
    DancersScore2("舞踏祭の楽譜＋", "Dancer's Score+", "舞會樂章＋"),
    DarkAura("共鳴オーラ", "Dark Aura", "共鳴輝光"),
    DarkBreath("闇のブレス", "Dark Breath", "暗之吐息"),
    DarkBreath2("闇のブレス＋", "Dark Breath+", "暗之吐息＋"),
    DarkExcalibur("共鳴エクスカリバー", "Dark Excalibur", "共鳴埃克斯卡利伯"),
    DarkGreatsword("黒き血の大剣", "Dark Greatsword", "黑血大劍"),
    DeathlyDagger("死神の暗器", "Deathly Dagger", "死神暗器"),
    DeftHarpoon("魚を突いた銛", "Deft Harpoon", "捕魚叉"),
    DeftHarpoon2("魚を突いた銛＋", "Deft Harpoon+", "捕魚叉＋"),
    DireThunder("ダイムサンダ", "Dire Thunder", "神雷"),
    DivineNaga("聖書ナーガ", "Divine Naga", "聖書那迦"),
    RefinedDivineNaga("聖書ナーガ", "Divine Naga", "聖書那迦"),
    DivineTyrfing("聖剣ティルフィング", "Divine Tyrfing", "聖劍斬裂劍"),
    Durandal("デュランダル", "Durandal", "迪朗達爾"),
    Eckesachs("エッケザックス", "Eckesachs", "艾坎札克斯"),
    Elfire("エルファイアー", "Elfire", "狂焰"),
    Elivagar("エリヴァーガル", "Elivagar", "Elivagar"),
    Elthunder("エルサンダー", "Elthunder", "狂雷"),
    Elwind("エルウィンド", "Elwind", "狂風"),
    EmeraldAxe("深緑の斧", "Emerald Axe", "深綠之斧"),
    EmeraldAxe2("深緑の斧＋", "Emerald Axe+", "深綠之斧＋"),
    Excalibur("エクスカリバー", "Excalibur", "埃克斯卡利伯"),
    FalchionA("ファルシオン(A)", "Falchion(A)", "法爾西昂(A)"),
    FalchionC("ファルシオン(C,L)", "Falchion(C,L)", "法爾西昂(C,L)"),
    FalchionM("ファルシオン(M)", "Falchion(M)", "法爾西昂(M)"),
    Fear("フィアー", "Fear", "恐懼"),
    Fear2("フィアー＋", "Fear+", "恐懼＋"),
    Fenrir("ノスフェラート", "Fenrir", "地獄之炎"),
    Fenrir2("ノスフェラート＋", "Fenrir+", "地獄之炎＋"),
    Fensalir("フェンサリル", "Fensalir", "芬薩里爾"),
    Fire("ファイアー", "Fire", "火焰"),
    FireBreath("火のブレス", "Fire Breath", "火之吐息"),
    FireBreath2("火炎のブレス", "Fire Breath+", "火焰吐息"),
    FiresweepBow("火薙ぎの弓", "Firesweep Bow", "火薙之弓"),
    FiresweepBow2("火薙ぎの弓＋", "Firesweep Bow+", "火薙之弓＋"),
    FiresweepLance("火薙ぎの槍", "Firesweep Lance", "火薙之槍"),
    FiresweepLance2("火薙ぎの槍＋", "Firesweep Lance+", "火薙之槍＋"),
    FiresweepSword("火薙ぎの剣", "Firesweep Sword", "火薙之劍"),
    FiresweepSword2("火薙ぎの剣＋", "Firesweep Sword+", "火薙之劍＋"),
    FirstBite("ファーストバイト", "First Bite", "定情之槍"),
    FirstBite2("ファーストバイト＋", "First Bite+", "定情之槍＋"),
    Flametongue("灼熱のブレス", "Flametongue", "灼熱吐息"),
    Flametongue2("灼熱のブレス＋", "Flametongue+", "灼熱吐息"),
    Flux("ミィル", "Flux", "流動"),
    Folkvangr("フォルクヴァング", "Folkvangr", "弗爾克范格"),
    FujinYumi("風神弓", "FujinYumi", "風神弓"),
    Geirskogul("ゲイルスケグル", "Geirskogul", "潔爾詩科古爾"),
    Gradivus("グラディウス", "Gradivus", "古拉迪烏斯"),
    Gravity("グラビティ", "Gravity", "重壓"),
    Gravity2("グラビティ＋", "Gravity+", "重壓＋"),
    GreenEgg("緑の卵", "Green Egg", "綠之卵"),
    GreenEgg2("緑の卵＋", "Green Egg+", "綠之卵＋"),
    Grimoire("グリモワール", "Grimoire", "魔法書"),
    Gronnblade("グルンブレード", "Gronnblade", "翠綠之刃"),
    Gronnblade2("グルンブレード＋", "Gronnblade+", "翠綠之刃＋"),
    Gronnowl("グルンアウル", "Gronnowl", "翠綠夜梟"),
    Gronnowl2("グルンアウル＋", "Gronnowl+", "翠綠夜梟＋"),
    Gronnraven("グルンレイヴン", "Gronnraven", "翠綠渡鴉"),
    Gronnraven2("グルンレイヴン＋", "Gronnraven+", "翠綠渡鴉＋"),
    Gronnwolf("グルンウルフ", "Gronnwolf", "翠綠餓狼"),
    Gronnwolf2("グルンウルフ＋", "Gronnwolf+", "翠綠餓狼＋"),
    GuardBow("遠距離防御の弓", "Guard  Bow", "遠距離防禦之弓"),
    GuardBow2("遠距離防御の弓＋", "Guard  Bow+", "遠距離防禦之弓＋"),
    Hammer("ハンマー", "Hammer", "戰錘"),
    Hammer2("ハンマー＋", "Hammer+", "戰錘＋"),
    Handbell("ハンドベル", "Handbell", "手鐘"),
    Handbell2("ハンドベル＋", "Handbell+", "手鐘＋"),
    Hauteclere("オートクレール", "Hauteclere", "奧特克雷勒"),
    HeavySpear("貫きの槍", "Heavy Spear", "貫穿之槍"),
    HeavySpear2("貫きの槍＋", "Heavy Spear+", "貫穿之槍＋"),
    HibiscusTome("ハイビスカスの本", "Hibiscus Tome", "扶桑花之書"),
    HibiscusTome2("ハイビスカスの本＋", "Hibiscus Tome+", "扶桑花之書＋"),
    IronAxe("鉄の斧", "Iron Axe", "鐵斧"),
    IronBow("鉄の弓", "Iron Bow", "鐵弓"),
    IronDagger("鉄の暗器", "Iron Dagger", "鐵暗器"),
    IronLance("鉄の槍", "Iron Lance", "鐵槍"),
    IronSword("鉄の剣", "Iron Sword", "鐵劍"),
    KeenBlarwolf("ブラーウルフ鍛", "Keen Blarwolf", "蒼藍餓狼鍛"),
    KeenBlarwolf2("ブラーウルフ鍛＋", "Keen Blárwolf+", "蒼藍餓狼鍛＋"),
    KeenGronnwolf("グルンウルフ鍛", "Keen Gronnwolf", "翠綠餓狼鍛"),
    KeenGronnwolf2("グルンウルフ鍛＋", "Keen Gronnwolf+", "翠綠餓狼鍛＋"),
    KeenRauorwolf("ラウアウルフ鍛", "Keen Rauðrwolf", "赤紅餓狼鍛"),
    KeenRauorwolf2("ラウアウルフ鍛＋", "Keen Rauðrwolf+", "赤紅餓狼鍛＋"),
    KillerAxe("キラーアクス", "Killer Axe", "必殺斧"),
    KillerAxe2("キラーアクス＋", "Killer Axe+", "必殺斧＋"),
    KillerBow("キラーボウ", "Killer Bow", "必殺弓"),
    KillerBow2("キラーボウ＋", "Killer Bow+", "必殺弓＋"),
    KillerLance("キラーランス", "Killer Lance", "必殺槍"),
    KillerLance2("キラーランス＋", "Killer Lance+", "必殺槍＋"),
    KillingEdge("キルソード", "Killing Edge", "必殺劍"),
    KillingEdge2("キルソード＋", "Killing Edge+", "必殺劍＋"),
    KittyPaddle("猫の暗器", "Kitty Paddle", "小貓暗器"),
    KittyPaddle2("猫の暗器＋", "Kitty Paddle+", "小貓暗器＋"),
    LegionsAxe("ローローの斧", "Legions Axe", "羅羅之斧"),
    LegionsAxe2("ローローの斧＋", "Legions Axe+", "羅羅之斧＋"),
    Leiptr("レイプト", "Leiptr", "雷依普特"),
    LightBreath("光のブレス", "Light Breath", "光之吐息"),
    LightBreath2("光のブレス＋", "Light Breath+", "光之吐息＋"),
    LightningBreath("雷のブレス", "Lightning Breath", "雷之吐息"),
    LightningBreath2("雷のブレス＋", "Lightning Breath+", "雷之吐息＋"),
    LilithFloatie("リリスの浮き輪", "Lilith Floatie", "莉莉絲的浮排"),
    LilithFloatie2("リリスの浮き輪＋", "Lilith Floatie+", "莉莉絲的浮排＋"),
    MelonCrusher("スイカ割りの棍棒", "MelonCrusher", "打西瓜的棍棒"),
    MelonCrusher2("スイカ割りの棍棒＋", "MelonCrusher+", "打西瓜的棍棒＋"),
    MonstrousBow("怪物の弓", "Monstrous Bow", "怪物弓"),
    MonstrousBow2("怪物の弓＋", "Monstrous Bow+", "怪物弓＋"),
    HamaYa("破魔矢", "Hama Ya", "Hama Ya"),
    HamaYa2("破魔矢＋", "Hama Ya+", "Hama Ya+"),
    Mulagir("ミュルグレ", "Mulagir", "妙爾葛雷"),
    Mystletainn("ミストルティン", "Mystletainn", "米斯特汀"),
    Naga("ナーガ", "Naga", "那迦"),
    RefinedNaga("ナーガ", "Naga", "那迦"),
    Nidhogg("ニーズヘッグ", "Nidhogg", "尼德霍格"),
    Noatun("ノーアトゥーン", "Noatun", "諾歐通"),
    Pain("ペイン", "Pain", "疼痛"),
    Pain2("ペイン＋", "Pain+", "疼痛＋"),
    Panic("パニック", "Panic", "慌亂"),
    Panic2("パニック＋", "Panic+", "慌亂＋"),
    Parthia("パルティア", "Parthia", "帕提亞"),
    PoisonDagger("秘毒の暗器", "Poison Dagger", "秘毒暗器"),
    PoisonDagger2("秘毒の暗器＋", "Poison Dagger+", "秘毒暗器＋"),
    Ragnarok("ライナロック", "Ragnarok", "末世烈焰"),
    Ragnell("ラグネル", "Ragnell", "ラグネル"),
    Raijinto("雷神刀", "Raijinto", "雷神刀"),
    Rauorblade("ラウアブレード", "Rauðrblade", "赤紅之刃"),
    Rauorblade2("ラウアブレード＋", "Rauðrblade+", "赤紅之刃"),
    Rauorowl("ラウアアウル", "Rauðrowl", "赤紅夜梟"),
    Rauorowl2("ラウアアウル＋", "Rauðrowl+", "赤紅夜梟＋"),
    Rauorraven("ラウアレイヴン", "Rauðrraven", "赤紅渡鴉"),
    Rauorraven2("ラウアレイヴン＋", "Rauðrraven+", "赤紅渡鴉＋"),
    Rauorwolf("ラウアウルフ", "Rauðrwolf", "赤紅餓狼"),
    Rauorwolf2("ラウアウルフ＋", "Rauðrwolf+", "赤紅餓狼＋"),
    RefreshingBolt("氷菓子の弓", "Refreshing Bolt", "冰品弓"),
    RefreshingBolt2("氷菓子の弓＋", "Refreshing Bolt+", "冰品弓＋"),
    RegalBlade("リガルブレイド", "Regal Blade", "帝王之劍"),
    ResoluteBlade("気鋭ワユの剣", "Resolute Blade", "氣銳瓦育之劍"),
    Rexcalibur("レクスカリバー", "Rexcalibur", "列克斯卡利伯"),
    Rexcalibur2("レクスカリバー＋", "Rexcalibur+", "列克斯卡利伯＋"),
    Ridersbane("ホースキラー", "Ridersbane", "殺馬槍"),
    Ridersbane2("ホースキラー＋", "Ridersbane+", "殺馬槍＋"),
    RogueDagger("盗賊の暗器", "Rogue Dagger", "盜賊暗器"),
    RogueDagger2("盗賊の暗器＋", "Rogue Dagger+", "盜賊暗器＋"),
    RubySword("旭日の剣", "Ruby Sword", "旭日之劍"),
    RubySword2("旭日の剣＋", "Ruby Sword+", "旭日之劍＋"),
    Ruin("ルイン", "Ruin", "破滅"),
    SackOGifts("プレゼント袋", "Sack o' Gifts", "禮物袋"),
    SackOGifts2("プレゼント袋＋", "Sack o' Gifts+", "禮物袋"),
    SapphireLance("蒼海の槍", "Sapphire Lance", "蒼海之槍"),
    SapphireLance2("蒼海の槍＋", "Sapphire Lance+", "蒼海之槍＋"),
    SealifeTome("熱帯魚の本", "Sealife Tome", "熱帶魚之書"),
    SealifeTome2("熱帯魚の本＋", "Sealife Tome+", "熱帶魚之書＋"),
    Seashell("貝殻", "Seashell", "貝殼"),
    Seashell2("貝殻＋", "Seashell+", "貝殼＋"),
    Siegfried("ジークフリート", "Siegfried", "西格弗里德"),
    Sieglinde("ジークリンデ", "Sieglinde", "齊格林德"),
    Siegmund("ジークムント", "Siegmund", "齊格蒙德"),
    SilverAxe("銀の斧", "Silver Axe", "銀斧"),
    SilverAxe2("銀の斧＋", "Silver Axe+", "銀斧＋"),
    SilverBow("銀の弓", "Silver Bow", "銀弓"),
    SilverBow2("銀の弓＋", "Silver Bow+", "銀弓＋"),
    SilverDagger("銀の暗器", "Silver Dagger", "銀暗器"),
    SilverDagger2("銀の暗器＋", "Silver Dagger+", "銀暗器＋"),
    SilverLance("銀の槍", "Silver Lance", "銀槍"),
    SilverLance2("銀の槍＋", "Silver Lance+", "銀槍＋"),
    SilverSword("銀の剣", "Silver Sword", "銀劍"),
    SilverSword2("銀の剣＋", "Silver Sword+", "銀劍＋"),
    SlayingAxe("キラーアクス鍛", "Slaying Axe", "必殺斧鍛"),
    SlayingAxe2("キラーアクス鍛＋", "Slaying Axe+", "必殺斧鍛＋"),
    SlayingBow("キラーボウ鍛", "Slaying Bow", "必殺弓鍛"),
    SlayingBow2("キラーボウ鍛＋", "Slaying Bow+", "必殺弓鍛＋"),
    SlayingEdge("キルソード鍛", "Slaying Edge", "必殺劍鍛"),
    SlayingEdge2("キルソード鍛＋", "Slaying Edge+", "必殺劍鍛＋"),
    SlayingHammer("ハンマー鍛", "Slaying Hammer+", "戰錘鍛"),
    SlayingHammer2("ハンマー鍛＋", "Slaying Hammer+", "戰錘鍛＋"),
    SlayingLance("キラーランス鍛", "Slaying Lance", "必殺槍鍛"),
    SlayingLance2("キラーランス鍛＋", "Slaying Lance+", "必殺槍鍛＋"),
    SlayingSpear("貫きの槍鍛", "Slaying Spear+", "貫穿之槍鍛"),
    SlayingSpear2("貫きの槍鍛＋", "Slaying Spear+", "貫穿之槍鍛＋"),
    Slow("スロウ", "Slow", "緩速"),
    Slow2("スロウ＋", "Slow+", "緩速＋"),
    SmokeDagger("紫煙の暗器", "Smoke Dagger", "紫煙暗器"),
    SmokeDagger2("紫煙の暗器＋", "Smoke Dagger+", "紫煙暗器＋"),
    SolKatti("ソール・カティ", "SolKatti", "索爾‧卡提"),
    SpectralTome("ゴーストの魔導書", "Spectral Tome", "惡靈魔道書"),
    SpectralTome2("ゴーストの魔導書+", "Spectral Tome+", "惡靈魔道書＋"),
    SteelAxe("鋼の斧", "Steel Axe", "鋼斧"),
    SteelBow("鋼の弓", "Steel Bow", "鋼弓"),
    SteelDagger("鋼の暗器", "Steel Dagger", "鋼暗器"),
    SteelLance("鋼の槍", "Steel Lance", "鋼槍"),
    SteelSword("鋼の剣", "Steel Sword", "鋼劍"),
    StoutTomahawk("剛斧トマホーク", "Stout  Tomahawk", "剛斧托馬霍克"),
    Tannenboom("聖樹", "Tannenboom", "聖樹"),
    Tannenboom2("聖樹＋", "Tannenboom!", "聖樹"),
    Thoron("トロン", "Thoron", "托隆"),
    Thoron2("トロン＋", "Thoron+", "托隆＋"),
    Thunder("サンダー", "Thunder", "雷電"),
    TomatoTome("トマトの本", "Tomato Tome", "番茄之書"),
    TomatoTome2("トマトの本＋", "Tomato Tome+", "番茄之書＋"),
    Tyrfing("ティルフィング", "Tyrfing", "斬裂劍"),
    Uror("ウルズ", "Uror", "烏爾德"),
    Urvan("ウルヴァン", "Urvan", "烏爾邦"),
    Valaskjalf("ヴラスキャルヴ", "Valaskjalf", "Valaskjalf"),
    Valflame("ファラフレイム", "Valflame", "法拉之炎"),
    Vidofnir("ヴィドフニル", "Vidofnir", "維德佛爾尼爾"),
    WaoDao("倭刀", "Wao Dao", "倭刀"),
    WaoDao2("倭刀＋", "Wao Dao+", "倭刀＋"),
    WeirdingTome("奇異ルーテの書", "Weirding Tome", "奇異盧特之書"),
    Wind("ウィンド", "Wind", "烈風"),
    Yato("夜刀神", "Yato", "夜刀神"),
    Zanbato("斬馬刀", "Zanbato", "斬馬刀"),
    Zanbato2("斬馬刀＋", "Zanbato+", "斬馬刀＋"),

    ArdentSacrifice("献身", "Ardent Sacrifice", "獻身"),
    Dance("踊る", "Dance", "Dance"),
    DrawBack("引き寄せ", "Draw Back", "拉近"),
    HarshCommand("一喝", "Harsh Command", "大喝"),
    Heal("ライブ", "Heal", "聖療"),
    Martyr("セインツ", "Martyr", "殉教"),
    Martyr2("セインツ＋", "Martyr+", "殉教＋"),
    Mend("リライブ", "Mend", "大聖療"),
    Physic("リブロー", "Physic", "遠程聖療"),
    Physic2("リブロー＋", "Physic+", "遠程聖療＋"),
    Pivot("回り込み", "Pivot", "迂迴"),
    RallyAtkDef("攻撃守備の応援", "Rally Attack Defense", "攻撃防守支援"),
    RallyAtkRes("攻撃魔防の応援", "Rally Attack Resistance", "攻撃魔防支援"),
    RallyAtkSpd("攻撃速さの応援", "Rally Attack Speed", "攻撃速度支援"),
    RallyAttack("攻撃の応援", "Rally Attack", "攻撃支援"),
    RallyDefRes("守備魔防の応援", "Rally Defense Resistance", "防守魔防支援"),
    RallyDefense("守備の応援", "Rally Defense", "防守支援"),
    RallyResistance("魔防の応援", "Rally Resistance", "魔防支援"),
    RallySpdDef("速さ守備の応援", "Rally Speed Defense", "速度防守支援"),
    RallySpdRes("速さ魔防の応援", "Rally Speed Resistance", "速度魔防支援"),
    RallySpeed("速さの応援", "Rally Speed", "速度"),
    ReciprocalAid("相互援助", "Reciprocal Aid", "相互援助"),
    Reconcile("ヒール", "Reconcile", "治療"),
    Recover("リカバー", "Recover", "聖癒"),
    Recover2("リカバー＋", "Recover+", "聖癒＋"),
    Rehabilitate("リバース", "Rehabilitate", "重生"),
    Rehabilitate2("リバース＋", "Rehabilitate+", "重生＋"),
    Reposition("引き戻し", "Reposition", "帶回"),
    Shove("体当たり", "Shove", "衝撞"),
    Sing("歌う", "Sing", "Sing"),
    Smite("ぶちかまし", "Smite", "重撃"),
    Swap("入れ替え", "Swap", "替換"),

    Daylight("陽影", "Daylight", "黎明"),
    Aegis("聖盾", "Aegis", "聖盾"),
    Aether("天空", "Aether", "天空"),
    RadiantAether("蒼の天空", "Radiant Aether", "蒼藍天空"),
    Astra("流星", "Astra", "流星"),
    BlackLuna("黒の月光", "Black Luna", "黒の月光"),
    BlazingFlame("烈火", "Blazing Flame", "烈火"),
    BlazingLight("烈光", "Blazing Light", "烈光"),
    BlazingThunder("烈雷", "Blazing Thunder", "烈雷"),
    BlazingWind("烈風", "Blazing Wind", "強風"),
    Bonfire("緋炎", "Bonfire", "緋炎"),
    Buckler("小盾", "Buckler", "小盾"),
    ChillingWind("氷点", "Chilling Wind", "冰點"),
    DragonGaze("伏竜", "Dragon Gaze", "臥龍"),
    DragonFang("竜穿", "Dragon Fang", "竜穿"),
    DraconicAura("竜裂", "Draconic Aura", "竜裂"),
    Escutcheon("長盾", "Escutcheon", "長盾"),
    Galeforce("疾風迅雷", "Galeforce", "疾風迅雷"),
    Glacies("氷華", "Glacies", "氷華"),
    Glimmer("凶星", "Glimmer", "凶星"),
    GlowingEmber("蛍火", "Glowing Ember", "蛍*火"),
    GrowingFlame("爆火", "Growing Flame", "爆火"),
    GrowingLight("爆光", "Growing Light", "爆光"),
    GrowingThunder("爆雷", "Growing Thunder", "爆雷"),
    GrowingWind("爆風", "Growing Wind", "爆風"),
    HeavenlyLight("天照", "Heavenly Light", "天照"),
    HolyVestments("聖衣", "Holy Vestments", "聖衣"),
    IceMirror("氷の聖鏡", "Ice Mirror", "氷の聖鏡"),
    Iceberg("氷蒼", "Iceberg", "冰蒼"),
    Ignis("華炎", "Ignis", "華炎"),
    Imbue("治癒", "Imbue", "治癒"),
    KindledFireBalm("業火の祝福", "Kindled Fire Balm", "業火的祝福"),
    Luna("月光", "Luna", "月光"),
    Miracle("祈り", "Miracle", "祈禱"),
    Moonbow("月虹", "Moonbow", "月虹"),
    NewMoon("影月", "NewMoon", "新月"),
    NightSky("星影", "NightSky", "星影"),
    Noontime("夕陽", "Noontime", "夕陽"),
    Pavise("大盾", "Pavise", "大盾"),
    RegnalAstra("剣姫の流星", "Regnal Astra", "劍姫的流星"),
    Reprisal("血讐", "Reprisal", "血仇"),
    Retribution("雪辱", "Retribution", "雪辱"),
    RisingFlame("砕火", "Rising Flame", "碎火"),
    RisingLight("砕光", "Rising Light", "碎光"),
    RisingThunder("砕雷", "Rising Thunder", "碎雷"),
    RisingWind("砕風", "Rising Wind", "碎風"),
    SacredCowl("聖兜", "Sacred Cowl", "甲"),
    Sol("太陽", "Sol", "太陽"),
    SolidEarthBalm("大地の祝福", "Solid Earth Balm", "大地的祝福"),
    StillWaterBalm("静水の祝福", "Still Water Balm", "靜水的祝福"),
    SwiftWindsBalm("疾風の祝福", "Swift Winds Balm", "疾風的祝福"),
    EarthwaterBalm("大地静水の祝福", "Earthwater Balm", "大地靜水的祝福"),
    EarthwaterBalm2("大地静水の祝福＋", "Earthwater Balm+", "大地靜水的祝福＋"),
    Vengeance("復讐", "Vengeance", "復仇"),

    AtkOpening("攻撃の開放", "Atk Opening", "攻擊開放"),
    SpdOpening("速さの開放", "Spd Opening", "速度開放"),
    DefOpening("守備の開放", "Def Opening", "防守開放"),
    ResOpening("魔防の開放", "Res Opening", "魔防開放"),
    ArmoredBlow("金剛の一撃", "Armored Blow", "金剛一擊"),
    AtkDef("攻撃守備", "Atk Def", "攻擊防守"),
    AtkDefBond("攻撃守備の絆", "Atk Def Bond", "攻擊防守的羈絆"),
    AtkRes("攻撃魔防", "Atk Res", "攻擊魔防"),
    AtkResBond("攻撃魔防の絆", "Atk Res Bond", "攻擊魔防的羈絆"),
    AtkSpd("攻撃速さ", "Atk Spd", "攻擊速度"),
    Attack("攻撃", "Attack", "攻擊"),
    BracingBlow("金剛明鏡の一撃", "Bracing Blow", "金剛明鏡擊"),
    BrazenAtkDef("攻撃守備の大覚醒", "Brazen Atk Def", "攻撃防守大覺醒"),
    BrazenAtkSpd("攻撃速さの大覚醒", "Brazen Atk Spd", "攻撃速度大覺醒"),
    BrazenAtkRes("攻撃魔防の大覚醒", "Brazen Atk Res", "攻撃魔防大覺醒"),
    CloseCounter("近距離反撃", "Close Counter", "近距離反擊"),
    CloseDef("近距離防御", "Close Def", "近距離防禦"),
    DartingBlow("飛燕の一撃", "Darting Blow", "飛燕一擊"),
    DeathBlow("鬼神の一撃", "Death Blow", "鬼神一擊"),
    Defense("守備", "Defense", "防守"),
    DefiantAtk("攻撃の覚醒", "Defiant Atk", "攻擊覺醒"),
    DefiantDef("守備の覚醒", "Defiant Def", "防守覺醒"),
    DefiantRes("魔防の覚醒", "Defiant Res", "魔防覺醒"),
    DefiantSpd("速さの覚醒", "Defiant Spd", "速度覺醒"),
    DistantCounter("遠距離反撃", "Distant Counter", "遠距離反擊"),
    DistantDef("遠距離防御", "Distant Def", "遠距離防禦"),
    EarthBoost("生命の大地", "Earth Boost", "生命的大地"),
    FierceStance("鬼神の構え", "Fierce Stance", "鬼神架勢"),
    DartingStance("飛燕の構え", "Darting Stance", "飛燕架勢"),
    FireBoost("生命の業火", "Fire Boost", "生命的業火"),
    FlashingBlade("柔剣", "Flashing Blade", "柔劍"),
    FortressDef("守備の城塞", "Fortress Def", "防守堡壘"),
    FortressRes("魔防の城塞", "Fortress Res", "魔防堡壘"),
    FortDefRes("守備魔防の城塞", "Fort. Def/Res", "防守魔防堡壘"),
    Fury("獅子奮迅", "Fury", "獅子奮迅"),
    GranisShield("グラニの盾", "Grani's Shield", "〇〇〇之盾"),
    HeavyBlade("剛剣", "Heavy Blade", "剛劍"),
    Hp("HP", "Hp", "HP"),
    HpDef("HP守備", "Hp Def", "HP防守"),
    HpRes("HP魔防", "Hp Res", "HP魔防"),
    HpSpd("HP速さ", "Hp Spd", "HP速度"),
    IotesShield("アイオテの盾", "Iote's Shield", "〇〇〇之盾"),
    LifeAndDeath("死線", "Life And Death", "死線"),
    MirrorStrike("鬼神明鏡の一撃", "Mirror Strike", "鬼神明鏡擊"),
    Resistance("魔防", "Resistance", "魔防"),
    SpdDef("速さ守備", "Spd Def", "速度防守"),
    SpdRes("速さ魔防", "Spd Res", "速度魔防"),
    DefRes("守備魔防", "Def Res", "防守魔防"),
    Speed("速さ", "Speed", "速度"),
    SteadyBlow("飛燕金剛の一撃", "Steady Blow", "飛燕金剛擊"),
    SteadyBreath("金剛の呼吸", "Steady Breath", "金剛の呼吸*"),
    SteadyStance("金剛の構え", "Steady Stance", "金剛架勢"),
    SturdyBlow("鬼神金剛の一撃", "Sturdy Blow", "鬼神金剛一擊"),
    SvalinnShield("スヴェルの盾", "Svalinn Shield", "〇〇〇之盾"),
    SwiftSparrow("鬼神飛燕の一撃", "Swift Sparrow", "鬼神飛燕擊"),
    SwiftStrike("飛燕明鏡の一撃", "Swift Strike", "飛燕明鏡擊"),
    TriangleAdept("相性激化", "Triangle Adept", "強化互克"),
    WardingBlow("明鏡の一撃", "Warding Blow", "明鏡一撃"),
    WardingBreath("明鏡の呼吸", "Warding Breath", "明鏡の呼吸*"),
    WardingStance("明鏡の構え", "Warding Stance", "明鏡架勢"),
    WaterBoost("生命の静水", "Water Boost", "生命的靜水"),
    WindBoost("生命の疾風", "Wind Boost", "生命的疾風"),

    AxeBreaker("斧殺し", "Axe Breaker", "破斧者"),
    BTomeBreaker("青魔殺し", "B Tome Breaker", "破青魔者"),
    BeorcsBlessing("ベオクの加護", "Beorc's Blessing", "貝歐克的加護"),
    BlazeDance("業火の舞い", "Blaze Dance", "業火之舞"),
    BoldFighter("攻撃隊形", "Bold Fighter", "攻擊隊形"),
    BowBreaker("弓殺し", "Bow Breaker", "破弓者"),
    BrashAssault("差し違え", "Brash Assault", "同〇〇〇"),
    CancelAffinity("相性相殺", "Cancel Affinity", "抵鋿*互克"),
    CrusadersWard("聖騎士の加護", "Crusaders Ward", "聖騎士的加護"),
    DaggerBreaker("暗器殺し", "Dagger Breaker", "破暗器者"),
    DazzlingStaff("幻惑の杖", "Dazzling Staff", "幻惑の杖"),
    Desperation("攻め立て", "Desperation", "猛攻"),
    DragBack("引き込み", "Drag Back", "引誘"),
    EscapeRoute("離脱の行路", "Escape Route", "脫離路線"),
    FlierFormation("編隊飛行", "Flier Formation", "編隊飛行"),
    FollowUpRing("追撃のリング", "Follow Up Ring", "追撃戒指"),
    GTomeBreaker("緑魔殺し", "G Tome Breaker", "破緑魔者"),
    GaleDance("疾風の舞い", "Gale Dance", "疾風之舞"),
    GeyserDance("大地静水の舞い", "Geyser Dance", "大地靜水之舞"),
    Guard("キャンセル", "Guard", "取消"),
    HitAndRun("一撃離脱", "Hit And Run", "一擊即離"),
    KnockBack("叩き込み", "Knock Back", "擊退"),
    LanceBreaker("槍殺し", "Lance Breaker", "破槍者"),
    LiveForBounty("豊穣の喜び", "Live For Bounty", "豊饒之喜悅"),
    LiveForHonor("栄誉の喜び", "Live For Honor", "榮〇之喜悅"),
    LiveToServe("ご奉仕の喜び", "Live To Serve", "奉〇〇〇〇"),
    Lunge("切り込み", "Lunge", "衝敵斬"),
    Obstruct("進軍阻止", "Obstruct", "阻止進軍"),
    Pass("すり抜け", "Pass", "穿越"),
    PoisonStrike("蛇毒", "Poison Strike", "蛇毒"),
    QuickRiposte("切り返し", "Quick Riposte", "回擊"),
    RTomeBreaker("赤魔殺し", "R Tome Breaker", "破赤魔者"),
    RecoverRing("リカバーリング", "Recover Ring", "聖癒戒指"),
    Renewal("回復", "Renewal", "回復"),
    SacaesBlessing("サカの加護", "Sacae's Blessing", "塞迦的加護"),
    SealAtk("攻撃封じ", "Seal Atk", "攻擊封印"),
    SealAtkDef("攻撃守備封じ", "Seal Atk Def", "攻擊防守封印"),
    SealAtkSpd("攻撃速さ封じ", "Seal Atk Spd", "攻擊速度封印"),
    SealDefRes("守備魔防封じ", "Seal Def Res", "防守魔防封印"),
    SealSpdDef("速さ守備封じ", "Seal Spd Def", "速度防守封印"),
    SealDef("守備封じ", "Seal Def", "防守封印"),
    SealRes("魔防封じ", "Seal Res", "魔防封印"),
    SealSpd("速さ封じ", "Seal Spd", "速度封印"),
    ShieldPulse("盾の鼓動", "Shield Pulse", "盾之躍動"),
    SwordBreaker("剣殺し", "Sword Breaker", "破劍者"),
    TorrentDance("静水の舞い", "Torrent Dance", "靜水之舞"),
    Vantage("待ち伏せ", "Vantage", "埋伏"),
    VengefulFighter("迎撃隊形", "Vengeful Fighter", "迎撃隊形"),
    WaryFighter("守備隊形", "Wary Fighter", "防守隊形"),
    Watersweep("水薙ぎ", "Watersweep", "水薙"),
    Windsweep("風薙ぎ", "Windsweep", "疾風横掃"),
    WingsOfMercy("救援の行路", "Wings of Mercy", "救援路線"),
    Wrath("怒り", "Wrath", "怒り"),
    WrathfulStaff("神罰の杖", "Wrathful Staff", "神罰之杖"),

    ArmorMarch("重装の行軍", "Armor March", "重装備行軍"),
    AtkPloy("攻撃の謀策", "Attack Ploy", "攻擊謀策"),
    AtkSmoke("攻撃の紫煙", "Attack Smoke", "攻擊紫煙"),
    AtkTactic("攻撃の指揮", "Atk Tactic", "攻擊指揮"),
    SpdTactic("速さの指揮", "Spd Tactic", "速度指揮"),
    AxeExperience("斧の経験", "Axe Experience", "斧之經驗"),
    AxeValor("斧の技量", "Axe Valor", "斧之技巧"),
    RTomeExperience("赤魔の経験", "R Tome Experience", "赤魔之經驗"),
    RTomeValor("赤魔の技量", "R Tome Valor", "赤魔之技巧"),
    BTomeExperience("青魔の経験", "B Tome Experience", "青魔之經驗"),
    BTomeValor("青魔の技量", "B Tome Valor", "青魔之技巧"),
    BowExperience("弓の経験", "Bow Experience", "弓之經驗"),
    BreathOfLife("生の息吹", "Breath of Life", "生命氣息"),
    DaggerValor("暗器の技量", "Dagger Valor", "暗器之技巧"),
    DefPloy("守備の謀策", "Def Ploy", "防守謀策"),
    DefTactic("守備の指揮", "Def Tactic", "防守の指揮"),
    ResTactic("魔防の指揮", "Res Tactic", "魔防の指揮"),
    DriveAtk("攻撃の大紋章", "Drive Atk", "攻擊大紋章"),
    DriveDef("守備の大紋章", "Drive Def", "防守大紋章"),
    DriveRes("魔防の大紋章", "Drive Res", "魔防大紋章"),
    DriveSpd("速さの大紋章", "Drive Spd", "速度大紋章"),
    FortifyBeasts("の鼓舞", "Fortify Beasts", "鼓舞"),
    FortifyArmor("重盾の鼓舞", "Fortify Armor", "重盾鼓舞"),
    FortifyCavalry("騎盾の鼓舞", "Fortify Cavalry", "騎盾鼓舞"),
    FortifyDef("守備の鼓舞", "Fortify Def", "防守鼓舞"),
    FortifyDragons("竜盾の鼓舞", "Fortify Dragons", "竜盾鼓舞"),
    FortifyFliers("飛盾の鼓舞", "Fortify Fliers", "飛盾鼓舞"),
    FortifyRes("魔防の鼓舞", "Fortify Res", "魔防鼓舞"),
    GTomeValor("緑魔の技量", "G Tome Valor", "緑魔之技巧"),
    GTomeExperience("緑魔の経験", "G Tome Experience", "緑魔之經驗"),
    GoadArmor("重刃の紋章", "Goad Armor", "重刃紋章"),
    GoadCavalry("騎刃の紋章", "Goad Cavalry", "騎刃紋章"),
    GoadDragons("竜刃の紋章", "Goad Dragons", "竜刃紋章"),
    GoadFliers("飛刃の紋章", "Goad Fliers", "飛刃紋章"),
    GoadBeasts("獣刃の紋章", "Goad Beasts", "獸刃紋章"),
        Guidance("空からの先導", "Guidance", "空中前導"),
    HoneBeasts("の鼓舞", "Hone Beasts", "鼓舞"),
    HoneArmor("重刃の鼓舞", "Hone Armor", "重刃鼓舞"),
    HoneAtk("攻撃の鼓舞", "Hone Atk", "攻擊鼓舞"),
    HoneCavalry("騎刃の鼓舞", "Hone Cavalry", "騎刃鼓舞"),
    HoneDragons("竜刃の鼓舞", "Hone Dragons", "竜刃鼓舞"),
    HoneFliers("飛刃の鼓舞", "Hone Fliers", "飛刃鼓舞"),
    HoneSpd("速さの鼓舞", "Hone Spd", "速度鼓舞"),
    InfantryPulse("歩行の鼓動", "Infantry Pulse", "歩行躍動"),
    LanceValor("槍の技量", "Lance Valor", "槍之技巧"),
    PanicPloy("恐慌の奇策", "Panic Ploy", "恐慌奇策"),
    ResPloy("魔防の謀策", "Res Ploy", "魔防謀策"),
    SavageBlow("死の吐息", "Savage Blow", "死亡氣息"),
    SpdPloy("速さの謀策", "Spd Ploy", "速度謀策"),
    SpdSmoke("速さの紫煙", "Spd Smoke", "速度紫煙"),
    SpurAtk("攻撃の紋章", "Spur Atk", "攻擊紋章"),
    SpurDef("守備の紋章", "Spur Def", "防守紋章"),
    SpurDefRes("守備魔防の紋章", "Spur Def Res", "防守魔防紋章"),
    SpurRes("魔防の紋章", "Spur Res", "魔防紋章"),
    SpurSpd("速さの紋章", "Spur Spd", "速度紋章"),
    SpurSpdDef("速さ守備の紋章", "Spur Spd Def", "速度防守紋章"),
    SwordExperience("剣の経験", "Sword Experience", "劍之經驗"),
    SwordValor("剣の技量", "Sword Valor", "劍之技量"),
    ThreatenAtk("攻撃の威嚇", "Threaten Atk", "攻擊威嚇"),
    ThreatenDef("守備の威嚇", "Threaten Def", "防守威嚇"),
    ThreatenRes("魔防の威嚇", "Threaten Res", "魔防威嚇"),
    ThreatenSpd("速さの威嚇", "Threaten Spd", "速度威嚇"),
    WardArmor("重盾の紋章", "Ward Armor", "重盾紋章"),
    WardCavalry("騎盾の紋章", "Ward Cavalry", "騎盾紋章"),
    WardDragons("竜盾の紋章", "Ward Dragons", "竜盾紋章"),
    WardFliers("飛盾の紋章", "Ward Fliers", "飛盾紋章"),
    WardBeasts("獣盾の紋章","Ward Beasts","獸盾紋章"),

    SquadAceA("第1迷宮の覇者", "Squad Ace A", "第1迷宮的霸王"),
    SquadAceB("第2迷宮の覇者", "Squad Ace B", "第2迷宮的霸王"),
    SquadAceC("第3迷宮の覇者", "Squad Ace C", "第3迷宮的霸王"),
    SquadAceD("第4迷宮の覇者", "Squad Ace D", "第4迷宮的霸王"),
    HardyBearing("不動の姿勢", "Hardy Bearing", "不動如山"),
    PhantomSpeed("速さの虚勢", "Phantom Speed", "速度誇飾"),
    QuickenedPulse("奥義の鼓動", "Quickened Pulse", "奥義之躍動"),
    DeflectMagic("連撃防御・魔", "Deflect Magic", "連擊防御・魔"),
    DeflectMelee("連撃防御・剣槍斧", "Deflect Melee", "連擊防禦・剣槍斧"),
    DeflectMissile("連撃防御・弓暗器", "Deflect Missile", "連擊防禦・弓暗器"),

    RefinedWeapon("錬成武器", "Refined Weapon", "Refined Weapon"),
    Range1Atk("攻撃(近)", "Atk(melee)", "攻擊(近)"),
    Range1Spd("速さ(近)", "Spd(melee)", "速度(近)"),
    Range1Def("守備(近)", "Def(melee)", "防守(近)"),
    Range1Res("魔防(近)", "Res(melee)", "魔防(近)"),

    Range2Atk("攻撃(遠)", "Atk(Ranged)", "攻擊(遠)"),
    Range2Spd("速さ(遠)", "Spd(Ranged)", "速度(遠)"),
    Range2Def("守備(遠)", "Def(Ranged)", "防守(遠)"),
    Range2Res("魔防(遠)", "Res(Ranged)", "魔防(遠)"),
    Pursuit("追撃", "Pursuit", "追撃"),
    SpecialDamage("奥義ダメージ＋10", "SpecialDamage", "奥義傷害+10"),
    Follow("追従", "Follow", "可移動至周圍2格"),
    MagicSuppression("魔法は反撃不能", "MagicSuppression", "魔法無法反擊"),
    AntiRangedWeapon("遠距離武器に対し攻撃+6", "Atk+6 if foe uses ranged weapon", "Atk+6 if foe uses ranged weapon"),
    BondFlyingAlly("飛行の味方がいる時攻撃魔防+5", "Atk/Res+5 with flying ally", "Atk/Res+5 with flying ally"),
    Nullify("特効対象の強化の+を無効にする", "Nullifies foe's bonuses", "抵鋿敵人的＋強化狀態"),
    Blizzard("ブリザード", "Blizzard", "暴風雪"),
    ChillingSeal("冰の封印", "Chilling Seal", "Chilling Seal"),
    EarthDance("大地の舞", "EarthDance", "大地之舞"),
    SpdDefBond("速さ守備の絆", "Spd Def Bond", "速度防守的羈絆"),
    Hagoita("羽子板", "Hagoita", "羽子板"),
    Hagoita2("羽子板＋", "Hagoita+", "羽子板＋"),
    Kadomatsu("門松", "Kadomatsu", "門松"),
    Kadomatsu2("門松＋", "Kadomatsu+", "門松＋"),
    KagamiMochi("鏡餅", "Kagami Mochi", "鏡餅麻糬"),
    KagamiMochi2("鏡餅＋", "Kagami Mochi+", "鏡餅麻糬＋"),
    Gleipnir("グレイプニル", "Gleipnir", "格萊普尼爾"),
    Ivaldi("イヴァルディ", "Ivaldi", "伊瓦爾蒂"),
    GreatFlame("神炎", "GreatFlame", "神炎吐息"),
    Naglfar("ナグルファル", "Naglfar", "納吉爾法"),
    BerserkArmads("狂斧アルマーズ", "Berserk Armads", "Berserk Armads"),
    GreenGift("緑のプレゼント箱", "GreenGift", "GreenGift"),
    GreenGift2("緑のプレゼント箱＋", "GreenGift+", "GreenGift"),
    BlueGift("青のプレゼント箱", "BlueGift", "BlueGift"),
    BlueGift2("青のプレゼント箱＋", "BlueGift+", "BlueGift"),
    Gratia("グラーティア", "Gratia", "Gratia"),
    Gratia2("グラーティア＋", "Gratia+", "Gratia+"),
    CasaBlanca("カサブランカ", "CasaBlanca", "CasaBlanca"),
    CasaBlanca2("カサブランカ＋", "CasaBlanca+", "CasaBlanca+"),

    HpAtk("HP攻撃", "HpAtk", "HP攻撃"),
    AtkSpdBond("攻撃速さの絆", "Atk/Spd Bond", "攻撃速度的羈絆"),
    DefResBond("守備魔防の絆", "Def/Res Bond", "防守魔防的羈絆"),
    BowValor("弓の技量", "Bow Valor", "弓之技巧"),

    ArmoredBoots("重装のブーツ", "Armored Boots", "Armored Boots"),

    AtkSpdDefRes2ToAllies("味方の攻撃速さ守備魔防+2", "Atk/Spd/Def/Res+2 to allies", "Atk/Spd/Def/Res+2 to allies"),
    AtkSpdDefRes4("攻撃速さ守備魔防+4", "Atk/Spd/Def/Res+4 if unit is adjacent to an ally", "Atk/Spd/Def/Res+4 if unit is adjacent to an ally"),
    doubleAttack("2回攻撃", "Double Attack", "Double Attack"),
    HinokasSpear("ヒノカの紅薙刀", "Hinoka's Spear", "Hinoka's Spear"),
    HinokasGuidance("先導", "Guidance", "前導"),
    Basilikos("バシリコス", "Basilikos", "Basilikos"),
    WingSword("ウィングソード", "Wing Sword", "Wing Sword"),
    FeliciasPlate("フェリシアの氷皿", "Felicia's Plate", "Felicia's Plate"),
    WarpPowder("転移の粉", "WarpPowder", "轉移粉末"),
    Thani("セイニー", "Thani", "賽尼"),
    Sacrifice("癒しの手", "Sacrifice", "治癒之手"),
    Peshkatz("ペシュカド", "Peshkatz", "佩修卡特"),
    SpurAtkSpd("攻撃速さの紋章", "Spur Atk Spd", "攻擊速度紋章"),

    FeliciasBlade("奥義カウント+1", "Special cooldown charge +1 if foe uses magic", "Special cooldown charge +1 if foe uses magic"),
    BrazenDefRes("守備魔防の大覚醒", "Brazen Def Res", "防守魔防大覺醒"),
    ChillDef("守備の封印", "Chill Def", "Chill Def"),
    ChillSpd("速さの封印", "Chill Spd", "Chill Spd"),
    Expiration("邪竜のブレス", "Expiration", "Expiration"),
    BelovedZofia("宝剣ソフィア", "Beloved Zofia", "Beloved Zofia"),
    Skadi("スカディ", "Skadi", "Skadi"),
    FlameSiegmund("炎槍ジークムント", "Flame Siegmund", "Flame Siegmund"),
    SturdyStance("鬼神金剛の構え", "Sturdy Stance", "鬼神金剛架勢"),
    SolarBrace("太陽の腕輪", "Solar Brace", "Solar Brace"),
    LunarBrace("月の腕輪", "Lunar Brace", "Lunar Brace"),
    SealedFalchion("封剣ファルシオン", "Sealed Falchion", "Sealed Falchion"),
    GrimasTruth("魔書ギムレー", "Grima's Truth", "Grima's Truth"),
    DullRanged("強化無効・遠距離", "Dull Ranged", "Dull Ranged"),
    Blarserpent("ブラーサーペント", "Blárserpent", "Blárserpent"),
    Blarserpent2("ブラーサーペント＋", "Blárserpent+", "Blárserpent+"),
    WindsBrand("深き印の風", "Wind's Brand", "Wind's Brand"),
    HuginnsEgg("フギンの魔卵", "Huginn's Egg", "Huginn's Egg"),
    ChillRes("魔防の封印", "Chill Res", "Chill Res"),
    MuninnsEgg("ムニンの魔卵", "Muninn's Egg", "Muninn's Egg"),
    SwiftStance("飛燕明鏡の構え", "Swift Stance", "Swift Stance"),
    GiantSpoon("ビッグスプーン", "Giant Spoon", "Giant Spoon"),
    GiantSpoon2("ビッグスプーン＋", "Giant Spoon+", "Giant Spoon+"),
    DefSmoke("守備の紫煙", "Def Smoke", "Def Smoke"),
    LethalCarrot("ベビーキャロット", "Lethal Carrot", "Lethal Carrot"),
    LethalCarrot2("ベビーキャロット＋", "Lethal Carrot+", "Lethal Carrot+"),
    SpdResBond("速さ魔防の絆", "Spd/Res Bond", "Spd/Res Bond"),


    MirrorStance("鬼神明鏡の構え", "Mirror Stance", "鬼神明鏡架勢"),
    Owl("Atk/Spd/Def/Res + 隣接ユニットx2", "Atk/Spd/Def/Res + allies × 2", "Atk/Spd/Def/Res + allies × 2"),
    Poleaxe("ポールアクス", "Poleaxe", "Poleaxe"),
    Poleaxe2("ポールアクス＋", "Poleaxe+", "Poleaxe+"),
    Dragonskin("邪竜の鱗", "Dragonskin", "Dragonskin"),
    ResSmoke("魔防の紫煙", "Res Smoke", "Res Smoke"),
    LightBrand("光の剣", "Light Brand", "Light Brand"),
    SDrink("Sドリンク", "S Drink", "S Drink"),
    Meisterschwert("マスターソード", "Meisterschwert", "Meisterschwert"),
    SpurAtkDef("攻撃守備の紋章", "Spur Atk/Def", "Spur Atk/Def"),
    SpurAtkRes("攻撃魔防の紋章", "Spur Atk/Res", "Spur Atk/Res"),
    WargodsTome("Wargod's Tome", "Wargod's Tome", "Wargod's Tome"),
    Restore("レスト", "Restore", "Restore"),
    Restore2("レスト＋", "Restore+", "Restore+"),
    Thunderhead("雷旋の書", "Thunderhead", "Thunderhead"),
    WarriorPrincess("戦姫の和弓", "Warrior Princess", "Warrior Princess"),
    FlierGuidance("飛行の先導", "Flier Guidance", "Flier Guidance"),
    HarmonicLance("倭鉾", "Harmonic Lance", "Harmonic Lance"),
    HarmonicLance2("倭鉾＋", "Harmonic Lance+", "Harmonic Lance+"),
    WaterBreath("水のブレス", "Water Breath", "Water Breath"),
    WaterBreath2("水のブレス＋", "Water Breath+", "Water Breath+"),
    SwiftMulagir("疾弓ミュルグレ", "Swift Mulagir", "Swift Mulagir"),
    LawsOfSacae("サカの掟", "Laws of Sacae", "Laws of Sacae"),
    BarbShuriken("暗殺手裏剣", "Barb Shuriken", "Barb Shuriken"),
    BarbShuriken2("暗殺手裏剣＋", "Barb Shuriken+", "Barb Shuriken+"),
    Forblaze("フォルブレイズ", "Forblaze", "Forblaze"),
    NamelessBlade("無名の一門の剣", "Nameless Blade", "Nameless Blade"),
    Rhomphaia("ロムファイア", "Rhomphaia", "Rhomphaia"),
    CamillasAxe("カミラの艶斧", "Camilla's Axe", "Camilla's Axe"),
    DarkMystletainn("魔剣ミストルティン", "Dark Mystletainn", "Dark Mystletainn"),
    Safeguard("守りの剣", "Safeguard", "Safeguard"),
    Safeguard2("守りの剣＋", "Safeguard+", "Safeguard+"),
    FirestormDance("業火疾風の舞い", "Firestorm Dance", "Firestorm Dance"),
    Mjolnir("トールハンマー", "Mjölnir", "Mjölnir"),
    OddAtkWave("攻撃の波・奇数", "Odd Atk Wave", "攻擊之波・奇數"),
    OddSpdWave("速さの波・奇数", "Odd Spd Wave", "速度之波・奇數"),
    OddResWave("魔防の波・奇数", "Odd Res Wave", "魔防之波・奇數"),
    Loptous("ロプトウス", "Loptous", "Loptous"),
    MuspellFireposy("ムスペルの炎花", "Múspell Fireposy", "Múspell Fireposy"),
    AtkFeint("攻撃の共謀", "Atk Feint", "Atk Feint"),
    SpdFeint("速さの共謀", "Spd Feint", "Spd Feint"),
    DefFeint("守備の共謀", "Def Feint", "Def Feint"),
    ResFeint("魔防の共謀", "Res Feint", "Res Feint"),
    FreshBouquet("清らかなブーケ", "Fresh Bouquet", "Fresh Bouquet"),
    FreshBouquet2("清らかなブーケ＋", "Fresh Bouquet+", "Fresh Bouquet+"),
    ChillAtk("攻撃の封印", "Chill Atk", "Chill Atk"),
    NiflFrostflowers("ニフルの氷花", "Nifl Frostflowers", "Nifl Frostflowers"),
    DefResLink("守備魔防の連携", "Def/Res Link", "Def/Res Link"),
    ArdentService("愛のケーキサーバ", "Ardent Service", "Ardent Service"),
    ArdentService2("愛のケーキサーバ＋", "Ardent Service+", "Ardent Service+"),
    Bushido("武士道", "Bushido", "Bushido"),
    KestrelStance("鬼神飛燕の構え", "Kestrel Stance", "Kestrel Stance"),
    VassalsBlade("剣姫の刀", "Vassal's Blade	", "Vassal's Blade"),
    EvenAtkWave("攻撃の波・偶数", "Even Atk Wave ", "Even Atk Wave"),
    EvenSpdWave("速さの波・偶数", "Even Spd Wave ", "Even Spd Wave"),
    GigaExcalibur("ギガスカリバー", "Giga Excalibur", "Giga Excalibur"),
    Aerobatics("曲技飛行", "Aerobatics", "Aerobatics"),
    TheCleaner("粛清の暗器", "The Cleaner", "The Cleaner"),
    TheCleaner2("粛清の暗器＋", "The Cleaner+", "The Cleaner+"),
    RefinedAura("杖か魔法の味方がいるときAtk/Spd+5", "a magic or staff ally, Atk/Spd+5", "a magic or staff ally, Atk/Spd+5"),
    BreathOfFog("霧のブレス", "Breath of Fog", "Breath of Fog"),
    RefinedBreathOfFog("剣か竜の味方がいるときAtk/Def+5", "a sword or dragon ally, Atk/Def+5", "a sword or dragon ally, Atk/Def+5"),
    FruitOfIdunn("イズンの果実", "Fruit of Iðunn", "Fruit of Iðunn"),
    AtkSpdPush("攻撃速さの渾身", "Atk/Spd Push", "Atk/Spd Push"),
    ShellLance("貝殻の槍", "Shell Lance", "Shell Lance"),
    ShellLance2("貝殻の槍＋", "Shell Lance+", "Shell Lance+"),
    DullClose("強化無効・近距離", "Dull Close", "Dull Close"),
    BeachBanner("ビーチフラッグ", "Beach Banner", "Beach Banner"),
    BeachBanner2("ビーチフラッグ＋", "Beach Banner+", "Beach Banner+"),
    Cocobow("ヤシの実の弓", "Cocobow", "Cocobow"),
    Cocobow2("ヤシの実の弓＋", "Cocobow+", "Cocobow+"),
    InfantryRush("歩行の剛撃", "Infantry Rush", "Infantry Rush"),
    ThunderArmoads("天雷アルマーズ", "Thunder Armoads", "Thunder Armoads"),
    OstiasPulse("オスティアの鼓動", "Ostia's Pulse", "Ostia's Pulse"),
    SummersBreath("真夏のブレス", "Summer's Breath", "Summer's Breath"),
    DragonValor("竜の技量", "Dragon Valor", "竜之技巧"),
    JuicyWave("南国のジュース", "Juicy Wave", "Juicy Wave"),
    JuicyWave2("南国のジュース＋", "Juicy Wave+", "Juicy Wave+"),
    FishieBow("魚の弓", "Fishie Bow", "Fishie Bow"),
    FishieBow2("魚の弓＋", "Fishie Bow+", "Fishie Bow+"),
    Starfish("ヒトデ", "Starfish", "Starfish"),
    Starfish2("ヒトデ＋", "Starfish+", "Starfish+"),
    DraconicPoleax("傭兵団の戦斧", "Draconic Poleax", "Draconic Poleax"),
    ReesesTome("カタリナの書", "Reese's Tome", "Reese's Tome"),
    DauntlessLance("義勇の槍", "Dauntless Lance", "Dauntless Lance"),
    ReprisalLance("反攻の槍", "Reprisal Lance", "Reprisal Lance"),
    ReprisalLance2("反攻の槍＋", "Reprisal Lance+", "Reprisal Lance+"),
    AtkSpdLink("攻撃速さの連携", "Atk/Spd Link", "Atk/Spd Link"),
    AtkDefLink("攻撃守備の連携", "Atk/Def Link", "Atk/Def Link"),
    AtkResLink("攻撃魔防の連携", "Atk/Res Link", "Atk/Res Link"),
    Trilemma("トリレンマ", "Trilemma", "Trilemma"),
    Trilemma2("トリレンマ＋", "Trilemma+", "Trilemma+"),
    StaffValor("杖の技量", "Staff Valor", "Staff Valor"),
    BeastValor("獣の技量", "Beast Valor", "獸之技巧"),
    Skuld("スクルド", "Skuld", "Skuld"),
    BracingStance("金剛明鏡の構え", "Bracing Stance", "Bracing Stance"),
    WoGun("倭棍", "Wo Gùn", "Wo Gùn"),
    WoGun2("倭棍＋", "Wo Gùn+", "Wo Gùn+"),
    Thogn("ソグン", "Thögn", "索軍"),
    FutureVision("未来を映す瞳", "Future Vision", "映照未來的眼眸"),
    DistantGuard("遠距離警戒", "Distant Guard", "遠距離警戒"),
    CloudMaiougi("緑雲の舞扇", "Cloud Maiougi", "綠雲舞扇"),
    CloudMaiougi2("緑雲の舞扇＋", "Cloud Maiougi+", "綠雲舞扇＋"),
    RockslideDance("疾風大地の舞い", "Rockslide Dance", "疾風大地之舞"),
    SkyMaiougi("青天の舞扇", "Sky Maiougi", "青天舞扇"),
    SkyMaiougi2("青天の舞扇＋", "Sky Maiougi+", "青天舞扇＋"),
    SpurSpdRes("速さ魔防の紋章", "Spur Spd Res", "速度魔防紋章"),
    DuskUchiwa("宵闇の団扇", "Dusk Uchiwa", "宵闇團扇"),
    DuskUchiwa2("宵闇の団扇＋", "Dusk Uchiwa+", "宵闇團扇＋"),
    OddDefWave("守備の波・奇数", "Odd Def Wave", "防守之波・奇數"),
    DawnSuzu("暁天の神楽鈴", "Dawn Suzu", "曉天的神樂鈴"),
    FirefloodDance("業火静水の舞い", "Fireflood Dance", "業火靜水之舞"),
    Hliðskjálf("フリズスキャルヴ", "Hliðskjálf", "至高王座之杖"),
    WindfireBalm("業火疾風の祝福", "Windfire Balm", "業火疾風的祝福"),
    WindfireBalm2("業火疾風の祝福＋", "Windfire Balm+", "業火疾風的祝福＋"),
    Garm("ガルム", "Garm", "加姆"),
    SpecialFighter("奥義隊形", "Special Fighter ", "奧義隊形"),
    RoyalSword("王家の剣", "Royal Sword", "王家之劍"),
    DoubleLion("獅子連斬", "Double Lion", "獅子連斬"),
    Maltet("マルテ", "Maltet", "馬爾堤"),
    OstianCounter("オスティアの反撃", "Ostian Counter", "奧斯提亞的反擊"),
    EvenResWave("魔防の波・偶数", "Even Res Wave", "魔防之波・偶數"),
    CloseGuard("近距離警戒", "Close Guard", "近距離警戒"),
    ExaltedFalchion("神剣ファルシオン", "Exalted Falchion", "神劍法爾西昂"),
    FireEmblem("炎の紋章", "Fire Emblem", "火焰紋章"),
    BindingShield("封印の盾", "Binding Shield", "封印之盾"),
    InfantryFlash("歩行の柔撃", "Infantry Flash", "步行之柔擊"),
    BarrierBlade("バリアの剣", "Barrier Blade", "巴里亞之劍"),
    BarrierBlade2("バリアの剣＋", "Barrier Blade+", "巴里亞之劍＋"),
    DelugeDance("疾風静水の舞い", "Deluge Dance", "疾風靜水之舞"),
    GaeBolg("ゲイボルグ", "Gáe Bolg", "蓋伯爾加"),
    RallySpdDef2("速さ守備の応援＋", "Rally Spd/Def+", "速度防守支援＋"),
    RallyAtkSpd2("攻撃速さの応援＋", "Rally Atk/Spd+", "攻擊速度支援＋"),
    RallyDefRes2("守備魔防の応援＋", "Rally Def/Res+", "防守魔防支援＋"),
    SteadyPosture("飛燕金剛の構え", "Steady Posture", "飛燕金剛架勢"),
    Forseti("フォルセティ", "Forseti", "弗魯賽提"),
    SpecialSpiral("奥義の螺旋", "Special Spiral", "奧義之螺旋"),
    HoarfrostKnife("霧氷のナイフ", "Hoarfrost Knife", "霧冰匕首"),
    RallyUpAtk("攻撃の大応援", "Rally Up Atk", "攻擊大支援"),
    RallyUpAtk2("攻撃の大応援＋", "Rally Up Atk+", "攻擊大支援＋"),
    RallyUpRes("魔防の大応援", "Rally Up Res", "魔防大支援"),
    RallyUpRes2("魔防の大応援＋", "Rally Up Res+", "魔防大支援＋"),
    Missiletainn("魔書ミステルトィン", "Missiletainn", "魔書米斯特丁"),
    AtkSpdSolo("攻撃速さの孤軍", "Atk/Spd Solo", "攻擊速度孤軍"),
    AtkDefSolo("攻撃守備の孤軍", "Atk/Def Solo", "攻擊防守孤軍"),
    AtkResSolo("攻撃魔防の孤軍", "Atk/Res Solo", "攻擊魔防孤軍"),
    DefResSolo("守備魔防の孤軍", "Def/Res Solo", "防守魔防孤軍"),
    SpdResLink("速さ魔防の連携", "Spd/Res Link", "速度魔防連動"),
    ShiningBow("シャイニングボウ", "Shining Bow", "閃耀弓"),
    ShiningBow2("シャイニングボウ＋", "Shining Bow+", "閃耀弓＋"),
    BreathOfBlight("暗夜竜のブレス", "Breath of Blight", "暗夜龍吐息"),
    EvenDefWave("守備の波・偶数", "Even Def Wave", "防守之波・偶數"),
    Niu("ニーウ", "Níu", "尼烏"),
    Laevatein("レーヴァテイン", "Laevatein", "瑞瓦提恩"),
    RDuelFlying("赤の死闘・飛行", "R Duel Flying", "赤色死鬥・飛行"),
    GDuelInfantry("緑の死闘・歩行", "G Duel Infantry", "綠色死鬥・步行"),
    CDuelInfantry("無の死闘・歩行", "C Duel Infantry", "無色死鬥・步行"),
    Byleistr("ビューレイスト", "Býleistr", "貝萊斯特"),
    Thokk("セック", "Thökk", "Thökk"),
    Sinmara("シンモラ", "Sinmara", "Sinmara"),
    FierceBreath("鬼神の呼吸", "Fierce Breath", "鬼神呼吸"),
    WithEveryone("みんなと一緒に", "With Everyone!", "和大家一起"),
    DivineMist("神霧のブレス", "Divine Mist", "神霧吐息"),

    CherchesAxe("セルジュの恐斧", "Cherche's Axe", "塞爾裘的恐斧"),
    OdinsGrimoire("オーディンの黒書", "Odin's Grimoire", "奧丁的黑書"),
    RefinedBrynhildr("2射程武器は追撃不能", "Ranged weapon cannot make follow-up attack", "Ranged weapon cannot make follow-up attack"),
    RefinedHinokasSpear("先導", "Guidance", "Guidance"),
    RefinedReesesTome("謀策", "Ploy", "Ploy"),
    RefinedRegalBlade("Atk/Spd/Def/Res+3", "Atk/Spd/Def/Res+3", "Atk/Spd/Def/Res+3"),
    RefinedSieglinde("Atk/Spd/Def/Res + allies buff", "Atk/Spd/Def/Res + allies buff", "Atk/Spd/Def/Res + allies buff"),
    RefinedYato("支援相手にAtk/Spd/Def/Res+4", "Atk/Spd/Def/Res+4 to support partner", "Atk/Spd/Def/Res+4 to support partner"),
    SpiritBreath("精霊のブレス", "Spirit Breath", "精靈吐息"),
    DevilishBow("コウモリの弓", "Devilish Bow", "蝙蝠弓"),
    DevilishBow2("コウモリの弓＋", "Devilish Bow+", "蝙蝠弓＋"),
    BottledJuice("果汁のボトル", "Bottled Juice", "玻璃果汁瓶"),
    BottledJuice2("果汁のボトル＋", "Bottled Juice+", "玻璃果汁瓶＋"),
    WitchyWand("キャンディの杖", "Witchy Wand", "糖果杖"),
    WitchyWand2("キャンディの杖＋", "Witchy Wand+", "糖果杖＋"),
    Sagittae("アロー", "Sagittae", "光箭"),
    BlueFlame("ブルーフレイム", "Blue Flame", "青之炎"),
    AversasNight("インバースの暗闇", "Aversa's Night", "茵巴絲的黑暗"),
    StormSieglinde("雷剣ジークリンデ", "Storm Sieglinde", "雷劍齊格林德"),
    BookOfShadows("泡影の書", "Book of Shadows", "泡影之書"),
    Flash("フラッシュ", "Flash", "閃爍"),
    Flash2("フラッシュ＋", "Flash+", "閃爍＋"),
    BookOfDreams("夢幻の書", "Book of Dreams", "夢幻之書"),
    DraconicRage("水の飛沫", "Draconic Rage", "水之飛沫"),
    NullFollowUp("見切り・追撃効果", "Null Follow-Up", "識破・追擊效果"),
    ShannasLance("シャニーの誓槍", "Shanna's Lance", "夏妮的誓槍"),
    AxeOfVirility("バアトルの豪斧", "Axe of Virility", "巴多爾的豪斧"),
    GoldenDagger("黄金の短剣", "Golden Dagger", "黃金短劍"),
    FlorinasLance("フロリーナの誓槍", "Florina's Lance", "芙羅利娜的誓槍"),
    SolitaryBlade("孤高の剣", "Solitary Blade", "Solitary Blade"),
    Sylgr("シュルグ", "Sylgr", "休爾格"),
    SorceryBlade("魔道の刃", "Sorcery Blade", "魔道之刃"),
    SurtrsMenace("炎王の威嚇", "Surtr's Menace", "炎王威嚇"),
    Imhullu("マフー", "Imhullu", "摩忽"),
    Gjoll("ギョッル", "Gjöll", "吉歐爾"),
    FreezingSeal("凍結の封印", "Freezing Seal", "凍結之封印"),
    GladiatorsBlade("剣闘士の剛剣", "Gladiator's Blade", "Gladiator's Blade"),
    WhitewingBlade("白騎の長剣", "Whitewing Blade", "白騎的長劍"),
    WhitewingLance("白騎の直槍", "Whitewing Lance", "白騎的直槍"),
    WhitewingSpear("白騎の短槍", "Whitewing Spear", "白騎的短槍"),
    ScarletSword("紅の剣", "Scarlet Sword", "Scarlet Sword"),
    TacticalGale("軍師の風書", "Tactical Gale", "Tactical Gale"),
    TacticalBolt("軍師の雷書", "Tactical Bolt", "Tactical Bolt"),
    TriangleAttack("トライアングルアタック", "Triangle Attack", "Triangle Attack"),
    Lyfjaberg("リフィア", "Lyfjaberg", "利菲亞"),
    MysticBoost("生命の護符", "Mystic Boost", "生命護符"),
    SparklingBoost("生命の輝き", "Sparkling Boost", "生命光輝"),
    JoyousLantern("ランタンの杖", "Joyous Lantern", "提燈之杖"),
    JoyousLantern2("ランタンの杖＋", "Joyous Lantern+", "提燈之杖＋"),
    GlitteringBreath("綺羅星のブレス", "Glittering Breath", "綺羅星吐息"),
    GlitteringBreath2("綺羅星のブレス＋", "Glittering Breath+", "綺羅星吐息＋"),
    FestiveSiegmund("業槍ジークムント", "Festive Siegmund", "業槍齊格蒙德"),
    GoodieBoot("冬祭のブーツ", "Goodie Boot", "冬祭之靴"),
    GoodieBoot2("冬祭のブーツ＋", "Goodie Boot+", "冬祭之靴＋"),
    PrayerWheel("清冷の法具", "Prayer Wheel", "清冷的法具"),
    GrayWaves("ユラリユルレリ", "Gray Waves", "悠悠搖曳"),
    BDuelFlying("青の死闘・飛行", "B Duel Flying", "青色死鬥・飛行"),
    Hikami("氷神刀", "Hikami", "冰神刀"),
    JointHoneSpd("速さの相互鼓舞", "Joint Hone Spd", "速度相互鼓舞"),
    Geishun("迎春の剣", "Geishun", "迎春之劍"),
    Geishun2("迎春の剣＋", "Geishun+", "迎春之劍＋"),
    KaburaYa("鏑矢", "Kabura Ya", "鳴鏑"),
    KaburaYa2("鏑矢＋", "Kabura Ya+", "鳴鏑＋"),
    Kumade("熊手", "Kumade", "草耙"),
    Kumade2("熊手＋", "Kumade+", "草耙＋"),
    EarthfireBalm("業火大地の祝福", "Earthfire Balm", "業火大地的祝福"),
    EarthfireBalm2("業火大地の祝福＋", "Earthfire Balm+", "業火大地的祝福＋"),
    Wagasa("和傘", "Wagasa", "和傘"),
    Wagasa2("和傘＋", "Wagasa+", "和傘＋"),

    HatchingFlier("幼獣の化身・飛行", "Hatching (Flier)", "幼獸化身・飛行"),
    FledglingFlier("若獣の化身・飛行", "Fledgling (Flier)", "若獸化身・飛行"),
    AdultFlier("成獣の化身・飛行", "Adult (Flier)", "成獸化身・飛行"),
    HawkKingClaw("鷹王の嘴爪", "Hawk King Claw", "鷹王之喙"),
    SturdyImpact("鬼神金剛の瞬撃", "Sturdy Impact", "鬼神金剛瞬擊"),
    WhelpInfantry("幼獣の化身・歩行", "Welp (Infantry)", "幼獸化身・步行"),
    YearlingInfantry("若獣の化身・歩行", "Yearling (Infantry)", "若獸化身・步行"),
    AdultInfantry("成獣の化身・歩行", "Adult (Infantry)", "成獸化身・步行"),
    WhelpCavalry("幼獣の化身・騎兵", "Welp (Cavalry)", "幼獸化身・步行"),
    YearlingCavalry("若獣の化身・騎兵", "Yearling (Cavalry)", "若獸化身・騎兵"),
    AdultCavalry("成獣の化身・騎兵", "Adult (Cavalry)", "成獸化身・騎兵"),
    WolfQueenFang("狼女王の牙", "Wolf Queen Fang", "狼女王之牙"),
    NullCDisrupt("見切り・反撃不可", "Null C-Disrupt", "識破・無法反擊"),
    Glare("邪眼", "Glare", "邪眼"),
    HeronWing("白鷺の翼", "Heron Wing", "白鷺之翼"),
    RavenKingBeak("鴉王の嘴爪", "Raven King Beak", "鴉王之喙"),

    ItsCurtains("のれん", "It's Curtains...", "門簾"),
    ItsCurtains2("のれん＋", "It's Curtains...+", "門簾＋"),
    RedHotDucks("赤いアヒル", "Red-Hot Ducks", "紅色小鴨"),
    RedHotDucks2("赤いアヒル＋", "Red-Hot Ducks+", "紅色小鴨＋"),
    Grandscratcher("孫の手", "Grandscratcher", "不求人"),
    Grandscratcher2("孫の手＋", "Grandscratcher+", "不求人＋"),
    FirefloodBalm("業火静水の祝福", "Fireflood Balm", "業火靜水的祝福"),
    FirefloodBalm2("業火静水の祝福＋", "Fireflood Balm+", "業火靜水的祝福＋"),
    SplashyBucket("神泉の風呂桶", "Splashy Bucket", "神泉木水盆"),
    SplashyBucket2("神泉の風呂桶＋", "Splashy Bucket+", "神泉木水盆＋"),
    AirOrders("先導の伝令・天", "Air Orders", "Air Orders"),
    OuchPouch("巾着袋", "Ouch Pouch", "束口袋"),
    OuchPouch2("巾着袋＋", "Ouch Pouch+", "束口袋＋"),
    TomeOfThoron("トロン", "Tome of Thoron", "托隆"),
    FellBreath("邪神のブレス","Fell Breath","邪神吐息"),
    Upheaval("メガクェイク","Upheaval","超級地震"),
    FaithfulAxe("祝祭の斧","Faithful Axe","祝祭之斧"),
    FaithfulAxe2("祝祭の斧＋","Faithful Axe+","祝祭之斧＋"),
    HeartsBlade("祝祭の剣","Heart's Blade","祝祭之劍"),
    HeartsBlade2("祝祭の剣＋","Heart's Blade+","祝祭之劍＋"),
    Gronnblooms("緑の花かご","Gronnblooms","綠之花籃"),
    Gronnblooms2("緑の花かご＋","Gronnblooms+","綠之花籃＋"),
    Blarblooms("青の花かご","Blárblooms","青之花籃"),
    Blarblooms2("青の花かご＋","Blárblooms+","青之花籃＋"),
    LoyalWreath("花輪","Loyal Wreath","花圈"),
    LoyalWreath2("花輪＋","Loyal Wreath+","花圈＋"),
    GradoPoleax("グラドの戦斧","Grado Poleax","格拉多的戰斧"),
    RefinedGradoPoleax("グラドの戦斧","Grado Poleax","格拉多的戰斧"),
    Silverbrand("真銀の聖剣","Silverbrand","純銀的聖劍"),
    IrissTome("アイリスの書","Iris's Tome","埃莉絲之書"),
    OborosSpear("オボロの漆薙刀","Oboro's Spear","朧的漆薙刀"),
    TharjasHex("サーリャの禁呪","Tharja's Hex","撒拉的禁咒"),
    RefinedTharjasHex("サーリャの禁呪","Tharja's Hex","撒拉的禁咒"),
    NilessBow("ゼロの虐弓","Niles's Bow","零的虐弓"),
    HinatasKatana("ヒナタの猛刀","Hinata's Katana","日向的猛刀"),
    WolfskinFang("人狼王の爪牙","Wolfskin Fang","狼人王的爪牙"),
WolfpupFang("人狼娘の爪牙","Wolfpup Fang","狼人之女的爪牙"),
    KitsuneFang("妖狐王の爪牙","Kitsune Fang","妖狐王的爪牙"),
    FoxkitFang("妖狐娘の爪牙","Foxkit Fang","妖狐之女的爪牙"),
    SabotageAtk("攻撃の混乱","Sabotage Atk","攻擊擾亂"),
    Dragonbind("魔竜封印の剣","Dragonbind","封印魔龍之劍"),
    BonusDoubler("強化増幅","Bonus Doubler","強化增幅"),
    HumanVirtue("人の可能性を！","Human Virtue","發揮人類的潛能！"),
    DemonicBreath("魔竜のブレス","Demonic Breath","魔龍吐息"),
    Vanguard("守りの槍","Vanguard","Vanguard"),
    Vanguard2("守りの槍＋","Vanguard+","Vanguard+"),
    Gronnserpent ("グルンサーペント","Gronnserpent","翠綠海蛇"),
    Gronnserpent2 ("グルンサーペント＋","Gronnserpent+","翠綠海蛇＋"),
    ShortBow ("短弓","Short Bow","短弓"),
    ShortBow2 ("短弓＋","Short Bow2","短弓＋"),
    EternalTome("悠久の書","Eternal Tome","悠久之書"),
    ArgentBow("銀の宝弓","Argent Bow","銀之寶弓"),
    ;
    /**
     * ロケールから対応する文字列を出す
     */
    fun localeName(l: Locale): String =
            when (l) {
                Locale.JAPANESE -> jp
                Locale.TAIWAN -> tw
                else -> us
            }

    override fun toString(): String = jp
}